@echo off
REM Gradle wrapper stub — full wrapper will be generated by Android Studio
echo ERROR: Gradle wrapper JAR not found.
echo Please open this project in Android Studio to generate the wrapper,
echo or run: gradle wrapper --gradle-version 8.7
exit /b 1
